### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by Maikoala** [Maikoala/protospace-31943#1]
#URL
 https://protospace-31943.herokuapp.com/

**Comment by TECHCAMP555** [comment]
Maikoalaさん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
・誤った情報では、そのページに留まる
→トップページに遷移されてしまします。

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by Maikoala** [comment]
確認ありがとうございます。

修正いたしましたので、ご確認お願いいたします。
（pull requestは作成していません）

**Comment by TECHCAMP555** [comment]
Maikoalaさん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
前回の修正箇所の指摘が言葉足らずでした。
申し訳ございません。

・新規投稿する際に誤った情報では、そのページに留まる
→トップページに遷移されてしまします。

修正し次第、以下のprotospace完了報告フォームを再度提出お願いします！
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by Maikoala** [comment]
ご確認ありがとうございます。
GitHubのリモートリポジトリにはpushしていたのですが、Herokuへpushしておりませんでした。
申し訳ありません。

どうぞよろしくお願いいたします。

**Comment by TECHCAMP555** [comment]
Maikoalaさん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

別途、最終課題の案内をチャンネルの方に送信させて頂きます。
今しばらくお待ちください。
